### ISSUE TITLE
How to add a procedure NodeCheckedChange ?

### ISSUE THREAD

**Issue by jcplu** [landgraf-dev/CheckTreeView#1]
Hello,
Is it possible to add a procedure MyTreeViewNodeCheckedChange(Sender: TObject; Node: TTreeNode) ?

**Comment by jcplu** [comment]
I can suggest this function to catch event from mouse.

function TTreeViewHelper.onNodeCheckedChangeFromMouse(Button: TMouseButton; Shift: TShiftState;
  X, Y: Integer; var Node: TTreeNode; OnCheckStateChanged: TCheckStateChangedProc = nil) : boolean;
begin
  if (htOnStateIcon in Self.GetHitTestInfoAt(X, Y)) then
  begin
    Node := Self.GetNodeAt(X, Y);
    if Node = nil then Node := Self.Selected;
    result:=true;
  end
  else
  begin
    Node := nil;
    result:=false;
  end;
end;

**Comment by wlandgraf** [comment]
That's what `HandleMouseDown` method is for. The sample shows how to do it.
